services:
  - type: web
    runtime: node
    name: Weather
    repo: https://github.com/areeves9/silver-octo-journey
    branch: main
    plan: free
    region: oregon
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node build/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
